# TCL File Generated by Component Editor 17.0
# Thu Aug 17 09:17:16 PDT 2017
# DO NOT MODIFY


# 
# arduino_configure "arduino_configure" v1.0
# Daniil Budanov 2017.08.17.09:17:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module arduino_configure
# 
set_module_property DESCRIPTION ""
set_module_property NAME arduino_configure
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Daniil Budanov"
set_module_property DISPLAY_NAME arduino_configure
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL arduino_configure
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file arduino_configure.v VERILOG PATH ip_src/arduino_configure.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL arduino_configure
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file arduino_configure.v VERILOG PATH ip_src/arduino_configure.v


# 
# parameters
# 
add_parameter REG_WIDTH INTEGER 32
set_parameter_property REG_WIDTH DEFAULT_VALUE 32
set_parameter_property REG_WIDTH DISPLAY_NAME REG_WIDTH
set_parameter_property REG_WIDTH TYPE INTEGER
set_parameter_property REG_WIDTH UNITS None
set_parameter_property REG_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REG_WIDTH HDL_PARAMETER true
add_parameter NUM_PWM INTEGER 8
set_parameter_property NUM_PWM DEFAULT_VALUE 8
set_parameter_property NUM_PWM DISPLAY_NAME NUM_PWM
set_parameter_property NUM_PWM TYPE INTEGER
set_parameter_property NUM_PWM ENABLED false
set_parameter_property NUM_PWM UNITS None
set_parameter_property NUM_PWM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_PWM HDL_PARAMETER true
add_parameter NUM_BUS INTEGER 3
set_parameter_property NUM_BUS DEFAULT_VALUE 3
set_parameter_property NUM_BUS DISPLAY_NAME NUM_BUS
set_parameter_property NUM_BUS TYPE INTEGER
set_parameter_property NUM_BUS ENABLED false
set_parameter_property NUM_BUS UNITS None
set_parameter_property NUM_BUS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_BUS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input REG_WIDTH
add_interface_port avalon_slave_0 addr address Input 4
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output REG_WIDTH
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point select_outputs
# 
add_interface select_outputs conduit end
set_interface_property select_outputs associatedClock ""
set_interface_property select_outputs associatedReset ""
set_interface_property select_outputs ENABLED true
set_interface_property select_outputs EXPORT_OF ""
set_interface_property select_outputs PORT_NAME_MAP ""
set_interface_property select_outputs CMSIS_SVD_VARIABLES ""
set_interface_property select_outputs SVD_ADDRESS_GROUP ""

add_interface_port select_outputs i2c_sel i2c_select Output 1
add_interface_port select_outputs pwm_sel pwm_select Output NUM_PWM
add_interface_port select_outputs spi_sel spi_select Output 1
add_interface_port select_outputs uart_sel uart_select Output 1

