# TCL File Generated by Component Editor 17.0
# Wed Jun 21 09:46:10 PDT 2017
# DO NOT MODIFY


# 
# pwm_bus "pwm_bus" v0.1
# Daniil Budanov 2017.06.21.09:46:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwm_bus
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwm_bus
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Daniil Budanov"
set_module_property DISPLAY_NAME pwm_bus
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm_bus
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm.v VERILOG PATH pwm/pwm.v
add_fileset_file pwm_bus.v VERILOG PATH pwm/pwm_bus.v {IS_CONFIGURATION_PACKAGE TOP_LEVEL_FILE}

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pwm_bus
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm.v VERILOG PATH pwm/pwm.v
add_fileset_file pwm_bus.v VERILOG PATH pwm/pwm_bus.v IS_CONFIGURATION_PACKAGE


# 
# parameters
# 
add_parameter BUS_WIDTH INTEGER 14 ""
set_parameter_property BUS_WIDTH DEFAULT_VALUE 14
set_parameter_property BUS_WIDTH DISPLAY_NAME BUS_WIDTH
set_parameter_property BUS_WIDTH TYPE INTEGER
set_parameter_property BUS_WIDTH UNITS None
set_parameter_property BUS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUS_WIDTH DESCRIPTION ""
set_parameter_property BUS_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 16 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH WIDTH ""
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input DATA_WIDTH
add_interface_port avalon_slave_0 addr address Input 4
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point signals
# 
add_interface signals conduit end
set_interface_property signals associatedClock ""
set_interface_property signals associatedReset ""
set_interface_property signals ENABLED true
set_interface_property signals EXPORT_OF ""
set_interface_property signals PORT_NAME_MAP ""
set_interface_property signals CMSIS_SVD_VARIABLES ""
set_interface_property signals SVD_ADDRESS_GROUP ""

add_interface_port signals pwm_sel sel Output BUS_WIDTH
add_interface_port signals pwm_sig sig Output BUS_WIDTH

