# TCL File Generated by Component Editor 17.1
# Sat Nov 25 00:18:35 EST 2017
# DO NOT MODIFY


# 
# spoofer "spoofer" v1.0
# Daniil Budanov 2017.11.25.00:18:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spoofer
# 
set_module_property DESCRIPTION ""
set_module_property NAME spoofer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Daniil Budanov"
set_module_property DISPLAY_NAME spoofer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spoofer_avst
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spoofer_avst.sv SYSTEM_VERILOG PATH ../tb/spoofer/spoofer_avst.sv TOP_LEVEL_FILE
add_fileset_file spoofer_counter.sv SYSTEM_VERILOG PATH ../tb/spoofer/spoofer_counter.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point avst
# 
add_interface avst avalon_streaming start
set_interface_property avst associatedClock clock
set_interface_property avst associatedReset reset
set_interface_property avst dataBitsPerSymbol 8
set_interface_property avst errorDescriptor ""
set_interface_property avst firstSymbolInHighOrderBits true
set_interface_property avst maxChannel 0
set_interface_property avst readyLatency 0
set_interface_property avst ENABLED true
set_interface_property avst EXPORT_OF ""
set_interface_property avst PORT_NAME_MAP ""
set_interface_property avst CMSIS_SVD_VARIABLES ""
set_interface_property avst SVD_ADDRESS_GROUP ""

add_interface_port avst ready ready Input 1
add_interface_port avst valid valid Output 1
add_interface_port avst data data Output DATA_WIDTH

